call_parentheses          = "Always"
collapse_simple_statement = "Always"
column_width              = 96
indent_type               = "Spaces"
indent_width              = 3
line_endings              = "Unix"
quote_style               = "AutoPreferDouble"
