# languages.toml -- helix language suppport configuration

# introduce the new language server (simple completions)
# installed via:
# $ cargo install --locked --git https://github.com/estin/simple-completion-language-server.git
# with instructions on the readme there.

[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
feature_words = true             # enable completion by word
feature_snippets = false         # disable snippets
snippets_first = false           # order of presentation
snippets_inline_by_word_tail = false # suggest snippets by WORD tail, for example `xsq|` becomes `x^2|` when
feature_unicode_input = false    # enable unicode input
feature_paths = false            # enable path completion
feature_citations = false        # enable citation completion

# write logs into the ~/.cache
[language-server.scls.environment]
RUST_LOG = "info,simple-completion-language-server=info"
LOG_FILE = "/Users/troi/.cache/simple-comletion-language-server/scls.log" 

# add scls to existing languages as desired. so far i only do this
# for pascal which does not have a functioning language server.

# toml configuration format:
#
# The lsp options appear to be taplo and tombi. Tombi appears to be well
# supported. I had some weird problems trying to get taplo to work with
# Neovim.
[[language]]
name = "toml"
auto-format = true
language-servers = ["tombi"]

# Pascal support is rather limited but it's not completely useless.
[[language]]
name = "pascal"
auto-format = false
scope = "source.pascal"
injection-regex = "pascal"
# file-types = ["pascal", "pas", "pp", "inc", "lpr", "lfm"]
file-types = [ "pascal", {glob = "*.pas"}, {glob = "*.p"}, {glob = "*.pp"}, {glob = "*.lpr"}, {glob = "*.lfm"}]
indent = { tab-width = 2, unit = " " }
block-comment-tokens = { start = "{", end = "}" }
# language-servers = ["pasls", "scls"]
language-servers = ["scls"]

[[language]]
name = "forth"
auto-format = false
scope = "source.forth"
block-comment-tokens = { start = "( ", end = " )" }
injection-regex = "forth"
file-types = [ "forth", {glob = "*.f" }, {glob = "*.fs"}, {glob = "*.fth"}]
indent = { tab-width = 4, unit = " " }
language-servers = ["scls"]
# "forth-lsp"]
# ### this needs to be built ###
# [language-server.pasls]
# command = "/Users/troi/Projects/pascal-language-server/lib/aarch64-darwin/pasls"
# args = []
#"--no-auto", "--dark-mode", "--enable-emoji", "--browser", "Safari"]
# [[language-server]]
# name = "pasls"
# command = { "/Users/troi/Projects/pascal-language-server/lib/aarch64-darwin/pasls", args=[] }
# [[grammar]]
# name = "pascal"
# source = { git = "https://github.com/Isopod/tree-sitter-pascal", rev = "2fd40f477d3e2794af152618ccfac8d92eb72a66" }

# The Go Language:
#
# There are several formatters available but gopls will use gofumpt if
# auto-format is on.
[[language]]
name = "go"
auto-format = true
language-servers = ["gopls"]

# Markdown (gfm) for text and prose:
#
# I have tried several lsp combinations for grammar, spelling, and preview,
# but I haven't found a perfect solution. I'm hoping Harper will fit my
# workflow and allow for a dictionary in a file. It seems that ltex-ls and
# variants don't do this, at least not for non-vscode configurations.
#
# - Marksman is the standard LSP
# - harper-ls is a grammar and spelling LSP.
# - mpls is a markdown preview server that supports Github Flavored Markdown.
# - replacing prettier with dprint.
[[language]]
name = "markdown"
file-types = ["md", {glob = "*.md"}]
# soft-wrap.enable = true
# soft-wrap.wrap-at-text-width = false
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
language-servers = ["marksman", "mpls", "harper-ls"]

# Language Server Settings.
#
# Tombi tells me it is not an accepted practice to group all of the
# entries relating to an entity together. Instead it wants the [[langauge]]
# definitions grouped and then the [language-server.*] definitions.

# Go has a "one true way" approach so there isn't much configuration
# needed.
[language-server.gopls.config]
gofumpt = true

# Only fire off the preview on demand.
[language-server.mpls]
command = "mpls"
args = ["--no-auto", "--dark-mode", "--enable-emoji", "--browser", "Safari"]

# Harper uses the usual stdin/stdout method of parsing. The more nitty-gritty
# settings under .config.harper-ls are copied from a sample I found with only
# a change to the dictionary location (so far).
[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.harper-ls.config.harper-ls]
userDictPath = "~/Notepad/harper-user-dictionary"
fileDictPath = "~/Notepad/harper-file-dictionaries"
diagnosticSeverity = "warning"
isolateEnglish = false
dialect = "American"

[language-server.harper-ls.config.harper-ls.linters]
SpellCheck = true
SpelledNumbers = false
AnA = true
SentenceCapitalization = false
UnclosedQuotes = true
WrongQuotes = false
LongSentences = true
RepeatedWords = true
Spaces = true
Matcher = true
CorrectNumberSuffix = true
ElipsisLength = false
ExpandStandardInputAndOutput = false
PhrasalVerbAsCompoundNoun = false
CapitalizePersonalPronouns = false
ExpandArgument = false
ExpandMinimum = false
ExpandMemoryShorthands = false
AvoidCurses = false
BoringWords = true
Months = false
ExpandTimeShorthands = false
